spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: create
  datasource:
    password: '${DB_PASSWORD}'
    username: '${DB_USERNAME}'
    url: jdbc:postgresql://localhost:8080/2drive

server:
  port: 8081

