spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
  datasource:
    password: '${DB_PASSWORD}'
    username: '${DB_USERNAME}'
    url: '${DB_URL}'
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8081

